services:

  redis:
    image: 'bitnami/redis:latest'
    command: redis-server
    volumes:
      - redis_data:/data
    environment:
      REDIS_ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - '6379:6379'

  postgresql:
    image: 'postgres:latest'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}

  business:
    build: ./business
    ports:
      - '3000:3000'
    volumes:
      - .:/business
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - postgresql
      - redis

  buisness_sidekiq:
    build: ./business
    command: bundle exec sidekiq
    volumes:
      - .:/business
    environment:
      RAILS_ENV: ${RAILS_ENV}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - redis

  # core:
  #   build: ./core
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/docker/app
  #   environment:
  #     RAILS_ENV: ${RAILS_ENV}
  #     DB_USER: ${DB_USER}
  #     DB_PASS: ${DB_PASS}
  #   depends_on:
  #     - db
  #     - redis

volumes:
  postgres_data:
  redis_data:
