version: '3.7'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
  web:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/myapp
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db

volumes:
  postgres:
