version: '3.7'

services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      REDIS_ALLOW_EMPTY_PASSWORD: ${REDIS_ALLOW_EMPTY_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "6380:6379"

  db:
    image: 'postgres:latest'
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}

  web:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
      - redis

volumes:
  postgres:
