source "https://rubygems.org"

ruby "3.3.6"

gem 'rails', '~> 8.0.0'

gem "pg", "~> 1.1"
gem 'strong_migrations'

gem "puma", ">= 5.0"

gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"

gem 'slim-rails', '~> 3.6.2'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

gem "bcrypt", "~> 3.1.7"

gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem 'faraday'

# dry-rb
gem 'dry-rails', '~> 0.7'
gem 'dry-events', '~> 1.0'
gem 'dry-struct', '~> 1.6'

gem 'sidekiq', '~> 7.3.6'
gem "redis", ">= 4.0.1"

group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
  gem 'dotenv', '~> 3.1.4'
end

group :development do
  gem "web-console"
  gem 'pry', '~> 0.14.2'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
