default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DEV_DB_USER'] %>
  password: <%= ENV['DEV_DB_PASS'] %>

development:
  <<: *default
  database: bookshop_development

test:
  <<: *default
  database: bookshop_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s