default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV['DB_USER'] %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  connect_timeout: 5
  variables:
    statement_timeout: 15s
    lock_timeout: 10s